server:
  port: 8585
spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource


# Logging configuration
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG